<h1>
	<?php echo "Welcome to our Blog" ?>
</h1>

<div class="clear"></div>
<?php $news = $this->getNews();
    if($news->count() < 1):
?>
	<div class="postWrapper">
	<p><?php echo Mage::helper('cmspro')->__('There is no news in this category'); ?></p>
	</div>
	<?php
	    else:
	    $newsThumbnailSize = $this->getNewsThumbnailSize();
	?>
	<div class="postWrapper">
	<?php foreach ($news as $n): 
		$url = Mage::getModel('core/url_rewrite')->load($n->getUrlRewriteId());
		?>
		<div class="cmspro_list_item">
		    <div class="cmspro_list_content">
		    	<div class="cmspro_list_summary">					
					<h3><a href="<?php echo Mage::getBaseUrl().$url->getRequestPath();?>"><?php echo $n->getTitle();?></a></h3>
					<?php $author ="";
	        		      $author = $n->getAuthor();
	        		      if($author != '') $author = Mage::helper('cmspro')->__(' | Posted by ').$author;?>
					<div class="posted-date"><?php echo Mage::helper('cmspro')->__('Published on ');?> <?php echo Mage::helper('core')->formatDate($n->getCreatedTime(),Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM).$author;?></div>
					<div>
						<?php echo substr($n->getSummary(),0,300)."..." ; ?>
						<a href="<?php echo Mage::getBaseUrl().$url->getRequestPath();?>"><?php echo Mage::helper('cmspro')->__('More');?></a>
					</div>
		    	</div>
		    	<div class="cmspro_list_images cmspro_list_mobile">
				   <img class="img-responsive" src="<?php echo $this->helper('cmspro/image')->init($n->getImages()) ?>" alt="<?php echo ('')?>"/>
				</div>
		    </div>
	    </div>  
	<?php endforeach; ?>		
		<?php 
			echo $this->getToolbarHtml(); 
		?> 
	</div>
<?php
    endif;
?>