<?php 
	$news = $this->getNews(); 
	if($news){
		$newsThumbnailSize = $this->getNewsThumbnailSize();
	?>
	<div class="postWrapper">
	     <div class="cmspro_postTitle">
	        <h1><div class="cmspro_postTitle_title"><?php echo $news->getTitle();?></div></h1>
	    </div>
	    
	    <div class="cmspro_news_content">
		    <?php if($news->getAllowShowImage()){?>
			   <img class="cmspro_news_images" src="<?php echo $this->helper('cmspro/image')->init($news->getImages()) ?>" alt="<?php echo('') ?>" />
		    <?php } ?>
		    
		    <?php echo $news->getContent(); ?>
		 </div>
	    
	    <div class="cmspro_postTitle_published">
        	<div><?php echo Mage::helper('cmspro')->__('Published on'); ?>
        	<?php $author ="";
        		  $author = $news->getAuthor();
        		  if($author != '') $author = Mage::helper('cmspro')->__(' | Posted by ').$author;?>
        	<?php echo Mage::helper('core')->formatDate($news->getCreatedTime(),Mage_Core_Model_Locale::FORMAT_TYPE_MEDIUM).$author;?></div>
        	
        	<div class="addthis"><?php echo $this->getChildHtml('cmspro.addthis');?></div>
        </div>
        
        
	    
	    <div class="cmspro_news_navigation">
		 	<?php $previous=$this->_getOlderNews(true);
		 	if($previous){ ?>
		 		<a class="cmspro_new_previous" href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($previous->getUrlRewriteId())->getRequestPath() ?>">
		 		<?php echo Mage::helper('cmspro')->__('&laquo; Previous'); ?></a>
		 	<?php } ?>
		 	
		 	<?php 
		 	$category = $this->_getCategory();
		 	if($category){ ?>
		 		<a class="cmspro_new_returncat" href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($category->getUrlRewriteId())->getRequestPath(); ?>">
		 		<?php echo Mage::helper('cmspro')->__('Return to the ').$category->getName(); ?></a>
		 	<?php } ?>
		 	<?php 
		 	$next = $this->_getNewerNews(true);
		 	if($next){ ?>
		 		<a class="cmspro_new_next" href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($next->getUrlRewriteId())->getRequestPath() ?>">
		 		<?php echo Mage::helper('cmspro')->__('Next &raquo;'); ?></a>
		 	<?php } ?>		 	
		 </div>
	    
	    <?php /* <div class="cmspro_news_relative">
			<?php if($this->_getNewerNews() && (sizeof($this->_getNewerNews()->getData())>0)){ ?>
				<h3><?php echo Mage::helper('cmspro')->__('Newer News'); ?></h3>
				<?php
				$newers = $this->_getNewerNews()->getData();
				for($i=(sizeof($newers)-1);$i>=0;$i--){?>
				<ul>
					<li><a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($newers[$i]['url_rewrite_id'])->getRequestPath(); ?>"><?php echo $newers[$i]['title']; ?></a></li>
				</ul>	
				<?php	}?>
			<?php } ?>
			</div> */ ?>
			
			<?php /* <div class="cmspro_news_relative">
			<?php  if($this->_getOlderNews() && (sizeof($this->_getOlderNews()->getData())>0)){ ?>
				<h3><?php echo Mage::helper('cmspro')->__('Older News'); ?></h3>
				<?php
				foreach($this->_getOlderNews() as $n){?>
				<ul>
					<li><a href="<?php echo Mage::getBaseUrl().Mage::getModel('core/url_rewrite')->load($n->getUrlRewriteId())->getRequestPath(); ?>"><?php echo $n->getTitle(); ?></a></li>
				</ul>	
				<?php	}?>
			<?php } ?>
			</div> */ ?>
	<?php echo $this->getChildHtml('product_additional_data');?>
	<?php echo $this->getChildHtml('cmspro_news_additional_data');?>
	</div>
	<?php }else{
		echo "Not found news!";
	}?>